language: node_js
node_js:
  - stable
notifications:
  email: false

script:
    - ./compiler.sh

before_install:
    - openssl aes-256-cbc -K $encrypted_6c76f6b5a723_key -iv $encrypted_6c76f6b5a723_iv -in deploy_key.enc -out deploy_key -d