language: node_js
node_js:
  - stable
notifications:
  email: false

before_script:
  - npm install -g aglio

script:
    - ./compiler.sh

before_install:
    - openssl aes-256-cbc -K $encrypted_6c76f6b5a723_key -iv $encrypted_6c76f6b5a723_iv -in deploy_key.enc -out deploy_key -d

after_success:
    - git config --global user.email "zarinpal@Travis"
    - git config --global user.name "zarinpal@Travis"
    - git config --global push.default simple
    - eval "$(ssh-agent -s)" #start the ssh agent
    - chmod 600 .travis_key # this key should have push access
    - ssh-add .travis_key
    - git clone git@github.com:ZarinPal-Lab/API-Docs.git
    - git checkout --orphan gh-pages
    - cp -rv index.html API-Docs
    - cd API-Docs
    - git add --all
    - git commit -m "Travis CI"
    - git push