
# Group Coupons

## list Coupons [/coupon.json]

Get list of current users Coupons

### List Coupons [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
  {
      "data": [
        {
          "entity_id": "57df865af29889001f6dce12",
          "code": "12345",
          "type": "webservice",
          "min_amount": "100",
          "discount": {
            "max_amount": "1111",
            "percent": "1"
          },
          "webservice_id": "57df865af29889001f6",
          "easypay_id": null,
          "limit": "2",
          "expired_at": "2021-02-20 01:01:00",
          "meta": {
            "code": 200
            }
        }
        ]
  }

  + Schema
  {
    "type" : "array",
    "items" : {
        "type" : "object",
        "properties" : {
            "entity_id" : {
                "type" : "string"
            },
            "code" : {
                "type" : "string",
                "description" : "coupon's code",
            },
            "type" : {
                "type" : "webservice",
                "description" : "if set webservice, this is for webservices .if set easypaym this is for easypays and if set all this for webservices and easypays"
            },
            "min_amount" : {
                "type" : "string",
                "description" : "This is min discount"
            },
            "discount" : {
                "type" : "object",
                "properties" : {
                    "max_amount" : {
                        "type" : "string",
                        "description" : "This is max discount"
                    },
                    "percent" : {
                        "type" : "string",
                        "description" : "This is percent discount"
                    }
                }
            },
            "webservice_id" : {
                "type" : "string"
            },
            "easypay_id" : {
                "type" : "string"
            },
            "limit" : {
                "type" : "string",
                "description" : "this is limit for coupon",
            },
            "expired_at" : {
                "type" : "string",
                "description" : "this is expiration date for coupon",
            }
        }
    }
}

## show Coupon [/coupon/[coupon_entity_id].json]

Get show information for one Coupon

### Show Coupon [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "CouponNotFound",
          "error_message": "The selected coupon not found or you are not allowed to use it."
        }
    }

+ Response 200 (application/json)

  + Body
  {
      "data" : {
          "entity_id": "57df865af29889001f6dce12",
          "code": "12345",
          "type": "webservice",
          "min_amount": "100",
          "discount": {
            "max_amount": "1111",
            "percent": "1"
          },
          "webservice_id": "57df865af29889001f6",
          "easypay_id": null,
          "limit": "2",
          "expired_at": "2021-02-20 01:01:00"
        },
        "meta": {
          "code": 200
        }
  }

  + Schema
  {
    "type" : "object",
    "properties" : {
        "entity_id" : {
            "type" : "string"
        },
        "code" : {
            "type" : "string",
            "description" : "coupon's code",
        },
        "type" : {
            "type" : "webservice",
            "description" : "if set webservice, this is for webservices . if set easypaym this is for easypays and if set all this for webservices and easypays"
        },
        "min_amount" : {
            "type" : "string",
            "description" : "This is min discount"
        },
        "discount" : {
            "type" : "object",
            "properties" : {
                "max_amount" : {
                    "type" : "string",
                    "description" : "This is max discount"
                },
                "percent" : {
                    "type" : "string",
                    "description" : "This is percent discount"
                }
            }
        },
        "webservice_id" : {
            "type" : "string"
        },
        "easypay_id" : {
            "type" : "string"
        },
        "limit" : {
            "type" : "string",
            "description" : "this is limit for coupon",
        },
        "expired_at" : {
            "type" : "string",
            "description" : "this is expiration date for coupon",
        }
    }
}

## new coupon [/coupon.json]

Request for new coupon

### New Coupon [POST]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Body
      {
          "code" : "22232",
        	"discount" : {
             "max_amount" : "333"
          },
          "webservice_id" : null,
        	"easypay_id" :"all",
        	"expired_at" : "2021-02-20 01:01:00",
        	"limit" : "12",
        	"min_amount" : "222222",
        	"type" : "webservice"
      }

    + Schema
    {
    "type" : "object",
    "properties" : {
        "code" : {
            "type" : "string",
            "description" : "coupon's code",
        },
        "discount" : {
            "type" : "object",
            "properties" : {
                "max_amount" : {
                    "type" : "string",
                    "description" : "This is max discount"
                },
                "percent" : {
                    "type" : "string",
                    "description" : "This is percent discount"
                }
            }
        },
        "webservice_id" : {
            "type" : "string"
        },
        "easypay_id" : {
            "type" : "string"
        },
        "expired_at" : {
            "type" : "string",
            "description" : "this is expiration date for coupon",
        },
        "limit" : {
            "type" : "string",
            "description" : "this is limit for coupon",
        },
        "type" : {
            "type" : "webservice",
            "description" : "if set webservice, this is for webservices . if set easypaym this is for easypays and if set all this for webservices and easypays"
        },
        "min_amount" : {
            "type" : "string",
            "description" : "This is min discount"
        }
    }
}

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "CouponExistsCode",
          "error_message": "The coupon already exists."
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "CouponExpired",
          "error_message": "The Coupon is expired."
        }
    }

+ Response 200 (application/json)

  + Body
  {
        "meta": {
          "code": 200,
          "message": "Create coupon successfully"
        }
  }

## edit coupon [/coupon/[coupon_entity_id].json]

Edit this coupon

### Edit  Coupon [PUT]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Body
    {
        "code" : "1111",
        "discount" : { "max_amount" : "333"},
        "expired_at" : "2021-02-20 01:01:00",
        "easypay_id" : null,
        "webservice_id" : "16d80a22-0d36-11e6-b4f0-000c295eb8fc",
        "limit" : "11",
        "min_amount" : "12345",
        "type" : "webservice"
    }

    + Schema
    {
      "type" : "object",
      "properties" : {
          "code" : {
              "type" : "string",
              "description" : "coupon's code",
          },
          "discount" : {
              "type" : "object",
              "properties" : {
                  "max_amount" : {
                      "type" : "string",
                      "description" : "This is max discount"
                  },
                  "percent" : {
                      "type" : "string",
                      "description" : "This is percent discount"
                  }
              }
          },
          "expired_at" : {
              "type" : "string",
              "description" : "this is expiration date for coupon",
          },
          "webservice_id" : {
              "type" : "string"
          },
          "easypay_id" : {
              "type" : "string"
          },
          "limit" : {
              "type" : "string",
              "description" : "this is limit for coupon",
          },
          "min_amount" : {
              "type" : "string",
              "description" : "This is min discount"
          },
          "type" : {
              "type" : "webservice",
              "description" : "if set webservice, this is for webservices . if set easypaym this is for easypays and if set all this for webservices and easypays "
          }
      }
  }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "CouponExistsCode",
          "error_message": "The coupon already exists."
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "CouponNotFound",
          "error_message": "The selected coupon not found or you are not allowed to use it."
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "CouponExpired",
          "error_message": "The Coupon is expired."
        }
    }

+ Response 200 (application/json)

  + Body
  {
        "meta": {
          "code": 200,
          "message": "Update coupon successfully"
        }
  }
