
# Group Tickets

## summery tickets [/ticket/summary.json]

List summary user's tickets

### Summary Tickets [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
    {
    "data": {
          "open": 1,
          "unread": 2
        },
        "meta": {
          "code": 200
        }
    }

  + Schema
    {
      "type": "object",
      "properties": {
        "open": {
          "type": "integer",
          "description": "open ticket's count number"
        },
        "unread": {
          "type": "integer",
          "description": "unread ticket's count number"
        }
      }
    }

## list tickets [/ticket.json]

List ticket of user

### List Tickets [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
  {
  "data": [
    {
      "title": "درخواست وب‌سرویس برای وب‌سایت test",
      "ticket_department_id": 1,
      "public_id": 139411070120,
      "priority": "normal",
      "status": "close",
      "read_status": {
        "first": true,
        "second": null
      },
      "created_at": "2016-01-27 15:43:40",
      "updated_at": "2016-09-24 13:26:31"
    }
    ],
    "meta": {
      "code": 200,
      "pagination": {
        "per_page": 10,
        "current_page": 1,
        "links": {
          "previous": null,
          "next": "https://api.zarinpal.com/rest/v3/ticket/index.json?page=2"
        }
      }
  }

  + Schema
  {
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "ticket_department_id": {
          "type": "integer",
          "description": "ticket's department"
        },
        "public_id": {
          "type": "integer"
        },
        "status": {
          "type": "string",
          "description": "ticket's status"
        },
        "read_status": {
          "type": "object",
          "properties": {
            "first": {
                "type" : "boolean",
                "description" : "if set true it's mean user read ticket else unread"
            },
            "second": {
                "type" : "boolean",
                "description" : "if set true it's mean secound user read ticket else unread"
            },
          },
          "created_at" : {
              "type" : "string"
          },
          "updated_at" : {
              "type" : "string"
          }
        }
      }
    }
  }

## show ticket [/ticket/[ticket_entity_id].json]

List replies of ticket

### show Ticket [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 400 (application/json)

    + Body
      {
          "meta": {
            "code": 400,
            "error_type": "TicketNotFound",
            "error_message": "Ticket Not Found."
          }
      }

+ Response 200 (application/json)

  + Body
    {
    "data": {
        "title": "درخواست وب‌سرویس برای وب‌سایت test",
        "ticket_department_id": 1,
        "public_id": 139411070120,
        "priority": "normal",
        "status": "close",
        "read_status": {
          "first": true,
          "second": null
        },
        "created_at": "2016-01-27 15:43:40",
        "updated_at": "2016-09-24 13:26:31",
        "replies": [
            {
              "content": "tes",
              "ip": "1.1.1.1",
              "attachment": null,
              "created_at": "2016-01-27 15:43:40",
              "user_info": {
                "name": "مسعود لطفي",
                "public_id": 111242,
                "email_hash": "9d8001efb3c5fcd82a73cc2e70a5"
              }
            }
          ]
        }
    }

    + Schema
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "ticket_department_id": {
            "type": "integer",
            "description": "ticket's department"
          },
          "public_id": {
            "type": "integer"
          },
          "status": {
            "type": "string",
            "description": "ticket's status"
          },
          "read_status": {
            "type": "object",
            "properties": {
              "first": {
                  "type" : "boolean",
                  "description" : "if set true it's mean user read ticket else unread"
              },
              "second": {
                  "type" : "boolean",
                  "description" : "if set true it's mean secound user read ticket else unread"
              },
            },
            "created_at" : {
                "type" : "string"
            },
            "updated_at" : {
                "type" : "string"
            }
          }
        }
      }
    }

## list department [/ticket/department.json]

List all department

### List Department [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
    {
       "data": [
         {
             "entity_id": 2,
            "name": "درخواست تاييد اطلاعات"
         },
       ],
       "meta": {
         "code": 200,
       },
    }

   + Schema
   {
      "type" : "array",
      "items" : {
         "type" : "object",
         "properties" : {
             "entity_id" : {
               "type" : "integer"
             },
             "name" : {
               "type" : "string"
             }
         }
      }
   }

## new ticket [/ticket.json]

Create new Ticket

### New Ticket [POST]

+ Request (application/json)

  + Headers
  Authorization: Bearer [access_token]

  + Body
    {
      "title" : "title of ticket",
      "content" : "content of ticket",
      "ticket_department_id" : 3,
      "priority" : 2
    }

  + Schema
    {
      "type" : "object",
      "properties" : {
        "title" : {
          "type" : "string",
        },
        "content" : {
          "type" : "string",
        },
        "ticket_department_id" : {
          "type" : "integer",
        },
        "priority" : {
          "type" : "integer"
        }
  }

+ Response 200 (application/json)

  + Body
    {
      "meta": {
          "code": 200,
          "message": "ticket create successfully."
      }
    }

## reply ticket [/ticket/[ticket_entity_id].json]

Reply new Ticket

### Reply Ticket [POST]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    +Body
      {
        "content" : "content of ticket",
        "attachment" : "null"
      }

    + Schema
      {
        "type" : "object",
        "properties" : {
          "content" : {
            "type" : "string",
          },
          "attachment" : {
            "type" : "strong",
            "description" : "upload file."
          }
        }
      }

+ Response 200 (application/json)

  + Body
    {
      "meta": {
          "code": 200,
          "message": "reply ticket send successfully"
      }
    }

## close ticket [/ticket/close/[ticket_public_id].json]

### Close Ticket [PUT]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Schema
      {
        "type" : "object",
        "properties" : {
          "ticket_public_id" : {
            "type" : "integer",
          }
        }
      }

+ Response 400 (application/json)

    + Body
      {
          "meta": {
            "code": 400,
            "error_type": "TicketNotFound",
            "error_message": "Ticket Not Found."
          }
      }

+ Response 200 (application/json)

  + Body
    {
      "meta": {
          "code": 200,
          "message": "ticket close successfully"
      }
    }

## create guest ticket [ticket/guest.json]

Create new Ticket for Guest

### Create Guest Ticket [POST]

+ Request (application/json)

  + Body
    {
    	"title" : "api test8",
    	"content" : "content api8",
    	"email" : "lion.masoud@yahoo.com",
    	"name"  : "masoud lotfi",
    	"phone" : "09351309626",
    	"ticket_department_id" : 3,
    	"priority" : 2
    }

  + Schema
    {
      "type" : "object",
      "properties" : {
        "title" : {
          "type" : "string",
        },
        "content" : {
          "type" : "string",
        },
        "email" : {
          "type" : "string",
        },
        "name" : {
          "type" : "string",
        },
        "phone" : {
          "type" : "string",
        },
        "ticket_department_id" : {
          "type" : "integer",
        },
        "priority" : {
          "type" : "integer"
        }
  }

+ Response 200 (application/json)

  + Body
    {
      "meta": {
          "code": 200,
          "message": "ticket create successfully"
      }
    }

## show ticket guest [ticket/guest/[hash_email]/[hash_ticket].json]

Find ticket guest

### Show Ticket Guest [GET]

+ Request (application/json)

+ Response 400 (application/json)

    + Body
      {
          "meta": {
            "code": 400,
            "error_type": "TicketNotFound",
            "error_message": "Ticket Not Found."
          }
      }

+ Response 200 (application/json)

  + Body
    {
    "data": {
        "title": "درخواست وب‌سرویس برای وب‌سایت test",
        "ticket_department_id": 1,
        "public_id": 139411070120,
        "priority": "normal",
        "status": "close",
        "read_status": {
          "first": true,
          "second": null
        },
        "created_at": "2016-01-27 15:43:40",
        "updated_at": "2016-09-24 13:26:31",
        "replies": [
            {
              "content": "tes",
              "ip": "1.1.1.1",
              "attachment": null,
              "created_at": "2016-01-27 15:43:40",
              "user_info": {
                "name": "مسعود لطفي",
                "phone": 09312345678,
                "email_hash": "9d8001efb3c5fcd82a73cc2e70a5"
              }
            }
          ]
        }
    }

    + Schema
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "ticket_department_id": {
            "type": "integer",
            "description": "ticket's department"
          },
          "public_id": {
            "type": "integer"
          },
          "status": {
            "type": "string",
            "description": "ticket's status"
          },
          "read_status": {
            "type": "object",
            "properties": {
              "first": {
                  "type" : "boolean",
                  "description" : "if set true it's mean user read ticket else unread"
              },
              "second": {
                  "type" : "boolean",
                  "description" : "if set true it's mean secound user read ticket else unread"
              },
            },
            "created_at" : {
                "type" : "string"
            },
            "updated_at" : {
                "type" : "string"
            }
          }
        }
      }
    }

## reply ticket guest [ticket/guest/[hash_email]/[hash_ticket].json]

Reply new Ticket

### Reply Ticket Guest [POST]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    +Body
      {
        "content" : "content of ticket",
        "attachment" : "null"
      }

    + Schema
      {
        "type" : "object",
        "properties" : {
          "content" : {
            "type" : "string",
          },
          "attachment" : {
            "type" : "strong",
            "description" : "upload file."
          }
        }
      }

+ Response 200 (application/json)

  + Body
    {
      "meta": {
          "code": 200,
          "message": "reply ticket send successfully"
      }
    }
