# Group Webservices

## list webservices [/webservice.json]

Get list of current users Webservice

### List Webservices [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceNotFound",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 200 (application/json)

  + Body
  {
      "data": [
        {
          "entity_id": "4a0b7ff2-67ac-11e6-b8c295eb8fc",
          "status": true,
          "purse": 1,
          "category_id": 10,
          "tel": "09122182569",
          "domain": "htpp://www.test.com",
          "ip": null,
          "name": "test",
          "description": "description for test",
          "ussd_id": null,
          "zaringate_status": "NotActivated",
          "logo": "//logoland.zarinpal.com/6e76cc60647c3d288631bf3ed444dd2b/125x125.png"
        ,
        "meta": {
          "code": 200
        }
      }
        ]
  }

  + Schema
  {
    "type" : "array",
    "items" : {
        "type" : "object",
        "properties" : {
            "entity_id" : {
                "type" : "string"
            },
            "status" : {
                "type" : "boolean",
                "description" : "if set status true this webservice is active else it's not Active",
            },
            "purse" : {
                "type" : "integer"
            },
            "category_id" : {
                "type" : "integer",
                "description" : "webservice's category"
            },
            "tel" : {
                "type" : "string"
            },
            "domain" : {
                "type" : "string"
            },
            "ip" : {
                "type" : "string",
                "description" : "if set ip is null ,this webservice not limited else it's on limited",
            },
            "name" : {
                "type" : "string"
            },
            "description" : {
                "type" : "string"
            },
            "ussd_id" : {
                "type" : "string",
                "description" : "code ussd"
            },
            "zaringate_status" : {
                "type" : "string",
                "description" : "check request for zaringate"
            },
            "logo" : {
                "type" : "string",
                "description" : "This is url for show logo"
            }
        }
    }
  }

## new webservice [/webservice.json]

Request for new webservice

### New Webservice [POST]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Body
      {
        "domain" : "www.test2.com",
        "tel" : "09351309626",
        "purse" : 1,
        "webservice_category_id" : 10,
        "site_name" : "test api",
        "site_content" : "test content for creeat webservice"
      }

    + Schema
    {
        "type" : "object",
        "properties" : {
            "purse" : {
                "type" : "integer"
            },
            "webservice_category_id" : {
                "type" : "integer",
                "description" : "webservice's category"
            },
            "tel" : {
                "type" : "string"
            },
            "domain" : {
                "type" : "string"
            },
            "site_name" : {
                "type" : "string"
            },
            "site_content" : {
                "type" : "string"
            }
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceNotFound",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceUniqueDomain",
          "error_message": "This Domain is exists."
        }
    }


+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceFreeDomain",
          "error_message": "This is a free domain."
        }
    }

+ Response 200 (application/json)

  + Body
  {
        "meta": {
          "code": 200,
          "message": "Post request for webservice successfully"
        }
  }

## edit webservice [/webservice/[webservice_entity_id].json]

Edit this webservice

### Edit  Webservice [PUT]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Body
      {
        "purse" : 2,
        "webservice_category_id" : 12,
        "site_ip" : 1.1.1.1,
      }

    + Schema
    {
        "type" : "object",
        "properties" : {
            "webservice" : {
                "type" : "string",
                "description" : "chose webservice"
            }
            "purse" : {
                "type" : "integer",
                "description" : "chose purse for this webservice"
            },
            "webservice_category_id" : {
                "type" : "integer",
                "description" : "chose webservice category for this webservice"
            },
            "site_ip" : {
                "type" : "string",
                "description" : "this limits webservice to this ip. optional",
            }
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceNotFound",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 200 (application/json)

  + Body
  {
        "meta": {
          "code": 200,
          "message": "Update webservice successfully"
        }
  }

## show price Zaringate for all webservices [/webservice/priceZaringate.json]

Get price for request zarin gate

### PRICE REQUEST ZARINGATE [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
  {
  "data": [
          {
            "webservice": "4a0b7ff2-67ac-11e000c295eb8fc",
            "amount": 20000
          }
      ],
      "meta": {
          "code": 200
      }
  }

  + Schema
  {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
            "webservice" : {
                "type" : "string",
                "description" : "webservice's entity_id"
            },
            "amount" : {
                "type" : "integer",
                "description" : "price zaringate for this webservice",
            }
        }
      }
  }

## show price Ussd for all webservices [/webservice/priceUssd.json]

Get price for ussd

### PRICE USSD[GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
  {
  "data": [
          {
            "webservice": "4a0b7ff2-67ac-11e000c295eb8fc",
            "amount": 20000
          }
      ],
      "meta": {
          "code": 200
      }
  }

  + Schema
  {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
            "webservice" : {
                "type" : "string",
                "description" : "webservice's entity_id"
            },
            "amount" : {
                "type" : "integer",
                "description" : "price ussd for this webservice",
            }
        }
      }
  }

## post request zaringate [/webservice/requestZaringate.json]

new Zaringate

### New Zaringate [POST]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Body
      {
          "webservice" : "e45d421e-3dd8-11e6-9399-0800279114ca",
          "purse" : 1
      }

    + Schema
    {
        "type" : "object",
        "properties" : {
            "webservice" : {
                "type" : "string",
                "description" : "request for this webservice."
            },
            "purse" : {
                "type" : "integer"
            }
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceNotFound",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 200 (application/json)

  + Body
  {
        "meta": {
          "code": 200,
          "message": "Send request for zarin gate successfully"
        }
  }

## post request ussd [/webservice/requestUssd.json]

Request new USSD

### Request New USSD [POST]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

    + Body
      {
          "webservice" : "e45d421e-3dd8-11e6-9399-0800279114ca",
          "purse" : 1,
          "ussd_id" : 12345
      }

    + Schema
    {
        "type" : "object",
        "properties" : {
            "webservice" : {
                "type" : "string",
                "description" : "request for this webservice."
            },
            "purse" : {
                "type" : "integer"
            },
            "ussd_id" : {
                "type" : "string",
                "description" : "ussd code"
            }
        }
    }

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceNotFound",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 200 (application/json)

  + Body
  {
        "meta": {
          "code": 200,
          "message": "Add ussd successfully"
        }
  }

## list WebserviceCategory [/webservice/category.json]

Get list of WebserviceCategory

### List WebserviceCategory [GET]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 200 (application/json)

  + Body
  {
      "data": [
      {
        "public_id": 1,
        "title": "خدمات اینترنت",
        "parent_id": null
      }
      ],
      "meta": {
        "code": 200
      }
  }

  + Schema
  {
    "type" : "array",
    "items" : {
        "type" : "object",
        "properties" : {
            "public_id" : {
                "type" : "integer"
            },
            "title" : {
                "type" : "string"
            },
            "parent_id" : {
                "type" : "integer",
                "description" : "for dropdown lists"
            },
            "category_id" : {
                "type" : "integer",
                "description" : "webservice's category"
            }
        }
    }
  }

## delete webservice [/webservice/[webservic_entity_id].json]

delete this webservice

### Delete Webservice [DELETE]

+ Request (application/json)

    + Headers
    Authorization: Bearer [access_token]

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "WebserviceNotFound",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 200 (application/json)

    + Body
    {
        "meta": {
          "code": 200,
          "message": "This Webservice delete successfully"
        }
    }

## Trust logo [/verifyWebsite/[domain].json]

### Trust Logo [GET]

+ Request (application/json)

+ Response 400 (application/json)

  + Body
    {
        "meta": {
          "code": 400,
          "error_type": "webserviceNotConfirm",
          "error_message": "Webservice Not Found."
        }
    }

+ Response 200 (application/json)

  + Body
  {
      "data": [
      {
        "domain": "test.ir",
        "name": "test",
        "updated": "2016-10-08 15:41:41",
        "logo": "//logoland.zarinpal.com/0ec15027fa4a8634fd16b5988a/125x125.png"
      }
      ],
      "meta": {
        "code": 200
      }
  }

  + Schema
  {
    "type" : "object",
    "properties" : {
        "domain" : {
            "type" : "string"
        },
        "name" : {
            "type" : "string"
        },
        "updated" : {
            "type" : "string"
        },
        "logo" : {
            "type" : "string"
        }
    }
  }
